###  A Multidimensional array object :

In [1]:
import numpy as np 

In [2]:
arr =np.random.randn(2,3)

In [3]:
arr

array([[ 0.47233385, -0.55206829, -0.28033961],
       [ 0.15516869,  0.96250767,  0.20639434]])

In [6]:
arr.shape

(2, 3)

In [8]:
arr.tobytes

<function ndarray.tobytes>

In [9]:
arr.dtype

dtype('float64')

In [11]:
arr * 10

array([[ 4.7233385 , -5.52068294, -2.80339612],
       [ 1.55168685,  9.62507671,  2.0639434 ]])

In [12]:
arr + arr 

array([[ 0.9446677 , -1.10413659, -0.56067922],
       [ 0.31033737,  1.92501534,  0.41278868]])

In [13]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

###  Creating ndarrays 

In [14]:
# 1d array 

In [16]:
data1 = [1,2,3,45,57,4,9]
arr =np.array(data1)
arr


array([ 1,  2,  3, 45, 57,  4,  9])

In [17]:
data2 = ([2,4,5,6,3,2,6,7],[2,6,8,4,2,5,0,8])
arr =np.array(data2)
arr


array([[2, 4, 5, 6, 3, 2, 6, 7],
       [2, 6, 8, 4, 2, 5, 0, 8]])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
arr.ndim

2

In [24]:
np.empty((2,3,2))

array([[[1.50692947e-312, 0.00000000e+000],
        [8.76794447e+252, 2.15895723e+227],
        [6.48224638e+170, 3.67145870e+228]],

       [[7.58253645e-096, 9.03292329e+271],
        [9.08366793e+223, 1.41075687e+232],
        [1.16070543e-028, 1.61117567e+295]]])

In [29]:
np.zeros_like((data1))

array([0, 0, 0, 0, 0, 0, 0])

In [47]:
np.linspace(1,3,3)

array([1., 2., 3.])

In [48]:
arr

array([[2, 4, 5, 6, 3, 2, 6, 7],
       [2, 6, 8, 4, 2, 5, 0, 8]])

In [49]:
ar =np.array([2,4,4,6,8,4,9,7])
ar

array([2, 4, 4, 6, 8, 4, 9, 7])

In [52]:
np.append(ar , 2)

array([2, 4, 4, 6, 8, 4, 9, 7, 2])

In [53]:
np.sort(ar)

array([2, 4, 4, 4, 6, 7, 8, 9])

In [57]:
np.delete(ar, 5)

array([2, 4, 4, 6, 8, 9, 7])

In [58]:
ar

array([2, 4, 4, 6, 8, 4, 9, 7])

In [59]:
np.delete(ar, 4)

array([2, 4, 4, 6, 4, 9, 7])

In [60]:
ar

array([2, 4, 4, 6, 8, 4, 9, 7])

In [61]:
ar[4]

8

In [63]:
arr2 =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
arr2.shape

(3, 4)

In [65]:
arr2.ndim

2

In [67]:
arr2.size

12

In [76]:
print("no. of rows", arr2.shape[0])

no. of rows 3


In [77]:
print("no. of columns", arr2.shape[1])

no. of columns 4


In [78]:
arr2[0]

array([1, 2, 3, 4])

In [84]:
arr

array([[2, 4, 5, 6, 3, 2, 6, 7],
       [2, 6, 8, 4, 2, 5, 0, 8]])

In [85]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [86]:
arr2[1,0]

5

In [87]:
arr2[1,1]

6

In [88]:
arr2[0,1]

2

In [91]:
arr2[0:2,:2]

array([[1, 2],
       [5, 6]])

In [92]:
arr2.min()

1

In [93]:
arr2.max()

12

In [94]:
arr2.sum()

78

In [101]:
arr2.size

12

In [97]:
arr2.shape

(3, 4)

In [106]:
rng.integers(6, size=(2,3))


NameError: name 'rng' is not defined

In [3]:
import numpy as np 

In [4]:
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i

In [5]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [9]:
arr[[1,4,2,5],[0,2,1,3]]

array([1., 4., 2., 5.])

In [10]:
arr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [11]:
arr.ravel()

array([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4.,
       4., 4., 4., 5., 5., 5., 5., 6., 6., 6., 6., 7., 7., 7., 7.])

In [12]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [13]:
arr.flatten()

array([0., 0., 0., 0., 1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4.,
       4., 4., 4., 5., 5., 5., 5., 6., 6., 6., 6., 7., 7., 7., 7.])

In [14]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [15]:
arr1 =np.array([[1,2,3],[4,5,6]])

In [16]:
arr2 =np.array([[7,8,9],[10,11,12]])

In [17]:
con =np.concatenate([arr1, arr2], axis=0)
con

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
con_f =np.concatenate([arr1, arr2], axis=1)
con_f

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [21]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [23]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [2]:
import numpy as np

In [8]:
arr3 =np.arange(3)
arr3
arr3.repeat(3)
arr3.repeat([1,2,3])

array([0, 1, 1, 2, 2, 2])

In [4]:
import numpy as np
arr4 =np.random.randn(4,4)
arr4
arr4.repeat(2, 0)

array([[-0.37829498, -0.28117513, -0.15664181, -0.15971142],
       [-0.37829498, -0.28117513, -0.15664181, -0.15971142],
       [-0.51259801, -0.12409883, -0.4616272 , -0.09877091],
       [-0.51259801, -0.12409883, -0.4616272 , -0.09877091],
       [-0.16141353, -0.35096178,  0.60210667, -0.38405112],
       [-0.16141353, -0.35096178,  0.60210667, -0.38405112],
       [-0.51177287, -0.53825139, -0.67980306, -2.12452284],
       [-0.51177287, -0.53825139, -0.67980306, -2.12452284]])

In [7]:
ar =np.arange(16).reshape(4,4)
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
ar.mean(1)

array([ 1.5,  5.5,  9.5, 13.5])

In [42]:
np.tile(ar, (2,3))

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15]])

NameError: name 'ar' is not defined

In [2]:
import numpy as np 

In [16]:
r =np.arange(16).reshape((2,2,4))
r

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [36]:
r.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [46]:
r1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
r1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
r1.transpose(1,0,2)

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [58]:
arr = np.random.randn(7) * 5
arr



array([  4.02459863,   8.3088973 ,   2.54706177,   0.3953865 ,
         3.16981882, -13.85574025,  -2.09739825])

In [60]:
remainder, whole_part = np.modf(arr)

In [61]:
remainder

array([ 0.02459863,  0.3088973 ,  0.54706177,  0.3953865 ,  0.16981882,
       -0.85574025, -0.09739825])

In [62]:
whole_part

array([  4.,   8.,   2.,   0.,   3., -13.,  -2.])

In [64]:
arr = np.random.randn(5, 2)
arr



array([[-0.43259526,  1.204658  ],
       [-0.330794  ,  0.76877025],
       [-0.61314735, -0.3675987 ],
       [ 0.27870485, -0.81880314],
       [-0.43069524,  0.58789904]])

In [68]:
first, second, third = np.split(arr, [1, 2])

In [78]:
np.split(arr, [3, 2])

[array([[-0.43259526,  1.204658  ],
        [-0.330794  ,  0.76877025],
        [-0.61314735, -0.3675987 ]]),
 array([], shape=(0, 2), dtype=float64),
 array([[-0.61314735, -0.3675987 ],
        [ 0.27870485, -0.81880314],
        [-0.43069524,  0.58789904]])]

In [80]:
r

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [84]:
ar =np.arange(16).reshape(4,4)
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
np.split(ar,[1,3])

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]